import Clean.Circuit
import Clean.Utils.Primes
import Ragu.Circuits.Element.AllocSquare
import Ragu.Circuits.Element.Mul
import Ragu.Circuits.Point.Spec

namespace Ragu.Circuits.Point.Alloc
variable {p : ℕ} [Fact p.Prime]

def main (curveParams : Spec.CurveParams (F p)) (_input : Unit) : Circuit (F p) (Var Spec.Point (F p)) := do
  let ⟨x, x2⟩ ← subcircuit Element.AllocSquare.circuit default
  let x3 ← subcircuit Element.Mul.circuit ⟨x, x2⟩
  let ⟨y, y2⟩ ← subcircuit Element.AllocSquare.circuit default

  -- NOTE: the constant (b * 1) is not simplified to b to syntactically
  -- match constraints generated by Ragu
  assertZero ((x3 + (curveParams.b * 1)) - y2)
  return ⟨x, y⟩

def Assumptions (_input : Unit) := True

def Spec (curveParams : Spec.CurveParams (F p)) (_input : Unit) (out : Spec.Point (F p)) :=
  out.isOnCurve curveParams

instance elaborated (curveParams : Spec.CurveParams (F p)) : ElaboratedCircuit (F p) unit Spec.Point where
  main := main curveParams
  localLength _ := 9

theorem soundness (curveParams : Spec.CurveParams (F p)) : Soundness (F p) (elaborated curveParams) Assumptions (Spec curveParams) := by
  circuit_proof_start
  simp [circuit_norm, Spec.Point.isOnCurve,
    Element.AllocSquare.circuit, Element.AllocSquare.Assumptions, Element.AllocSquare.Spec,
    Element.Mul.circuit, Element.Mul.Assumptions, Element.Mul.Spec, Element.Mul.main] at h_holds ⊢
  obtain ⟨c1, c2, c3, c4⟩ := h_holds
  rw [add_neg_eq_zero, c2, c1, c3] at c4
  rw [←c4]
  ring

theorem completeness (curveParams : Spec.CurveParams (F p)) : Completeness (F p) (elaborated curveParams) Assumptions := by
  sorry

def circuit (curveParams : Spec.CurveParams (F p)) : FormalCircuit (F p) unit Spec.Point :=
  {
    (elaborated curveParams) with
    Assumptions,
    Spec := (Spec curveParams),
    soundness := soundness curveParams,
    completeness := completeness curveParams
  }

end Ragu.Circuits.Point.Alloc
