import Clean.Circuit
import Clean.Utils.Primes
import Ragu.Circuits.Element.AllocSquare
import Ragu.Circuits.Element.Mul

namespace Ragu.Circuits.Point.Alloc
variable {p : ℕ} [Fact p.Prime]

structure Point (F : Type) where
  x : F
  y : F
deriving ProvableStruct

def main (_input : Unit) : Circuit (F p) (Var Point (F p)) := do

  let ⟨x, x2⟩ ← subcircuit Element.AllocSquare.circuit default
  let x3 ← subcircuit Element.Mul.circuit ⟨x, x2⟩
  let ⟨y, y2⟩ ← subcircuit Element.AllocSquare.circuit default

  -- NOTE: the constant (5 * 1) is not simplified to 5 to syntactically
  -- match constraints generated by Ragu
  assertZero ((x3 + (5 * 1)) - y2)
  return ⟨x, y⟩

def Assumptions (_input : Unit) := True

def Spec (_input : Unit) (out : Point (F p)) :=
  out.y^2 = out.x^3 + 5

instance elaborated : ElaboratedCircuit (F p) unit Point where
  main
  localLength _ := 9

theorem soundness : Soundness (F p) elaborated Assumptions Spec := by
  circuit_proof_start
  simp [circuit_norm,
    Element.AllocSquare.circuit, Element.AllocSquare.Assumptions, Element.AllocSquare.Spec,
    Element.Mul.circuit, Element.Mul.Assumptions, Element.Mul.Spec, Element.Mul.main] at h_holds ⊢
  obtain ⟨c1, c2, c3, c4⟩ := h_holds
  rw [add_neg_eq_zero, c2, c1, c3] at c4
  rw [←c4]
  ring

theorem completeness : Completeness (F p) elaborated Assumptions := by
  sorry

def circuit : FormalCircuit (F p) unit Point :=
  { elaborated with Assumptions, Spec, soundness, completeness }

end Ragu.Circuits.Point.Alloc
