import Clean.Circuit
import Clean.Utils.Primes
import Ragu.Circuits.Element.AllocSquare
import Ragu.Circuits.Element.Mul
import Ragu.Circuits.Point.Spec

namespace Ragu.Circuits.Point.Alloc
variable {p : ℕ} [Fact p.Prime]

-- 3 AllocMul instances: idx for AllocSquare(x), idx+1 for Mul(x,x²), idx+2 for AllocSquare(y)
--
-- Semantically equivalent to:
--   let ⟨x, x2⟩ ← Element.AllocSquare.circuit idx default
--   let x3 ← Element.Mul.circuit (idx + 1) ⟨x, x2⟩
--   let ⟨y, y2⟩ ← Element.AllocSquare.circuit (idx + 2) default
--   assertZero ((x3 + (curveParams.b * 1)) - y2)
--   return ⟨x, y⟩
--
-- Inlined to raw witness + assertZero for completeness proof access to env-readRow mappings.
-- To undo this inlining, the Clean framework needs to expose how sub-circuit witnesses
-- map to environment entries (i.e., connect readRow indices to env.get offsets).
def main (curveParams : Spec.CurveParams p) (idx : ℕ) (_input : Unit) : Circuit (F p) (Var Spec.Point (F p)) := do
  -- AllocSquare(x): idx
  let ⟨w0x, w0y, w0z⟩ ← (witness fun env => Core.AllocMul.readRow env.data idx
    : Circuit (F p) (Var Core.AllocMul.Row (F p)))
  assertZero (w0x * w0y - w0z)
  assertZero (w0x - w0y)
  -- Mul(x, x²): idx+1
  let ⟨w1x, w1y, w1z⟩ ← (witness fun env => Core.AllocMul.readRow env.data (idx + 1)
    : Circuit (F p) (Var Core.AllocMul.Row (F p)))
  assertZero (w1x * w1y - w1z)
  assertZero (w1x - w0x)
  assertZero (w1y - w0z)
  -- AllocSquare(y): idx+2
  let ⟨w2x, w2y, w2z⟩ ← (witness fun env => Core.AllocMul.readRow env.data (idx + 2)
    : Circuit (F p) (Var Core.AllocMul.Row (F p)))
  assertZero (w2x * w2y - w2z)
  assertZero (w2x - w2y)
  -- NOTE: the constant (b * 1) is not simplified to b to syntactically
  -- match constraints generated by Ragu
  assertZero ((w1z + (curveParams.b * 1)) - w2z)
  return ⟨w0x, w2x⟩

def Assumptions (curveParams : Spec.CurveParams p) (idx : ℕ) (_input : Unit) (data : ProverData (F p)) :=
  Element.AllocSquare.Assumptions idx () data ∧
  -- Mul(x, x²): witness binding (inlined, was Element.Mul.Assumptions)
  (let w := Core.AllocMul.readRow data (idx + 1)
   w.x = (Core.AllocMul.readRow data idx).x ∧
   w.y = (Core.AllocMul.readRow data idx).z) ∧
  Element.AllocSquare.Assumptions (idx + 2) () data ∧
  -- Curve equation: x³ + b = y²
  (Core.AllocMul.readRow data (idx + 1)).z + curveParams.b = (Core.AllocMul.readRow data (idx + 2)).z

def Spec (curveParams : Spec.CurveParams p) (_input : Unit) (out : Spec.Point (F p)) (_data : ProverData (F p)) :=
  out.isOnCurve curveParams

instance elaborated (curveParams : Spec.CurveParams p) (idx : ℕ) : ElaboratedCircuit (F p) unit Spec.Point where
  main := main curveParams idx
  localLength _ := 9

theorem soundness (curveParams : Spec.CurveParams p) (idx : ℕ) : GeneralFormalCircuit.Soundness (F p) (elaborated curveParams idx) (Spec curveParams) := by
  circuit_proof_start
  simp only [Spec.Point.isOnCurve] at ⊢
  simp only [List.sum, List.foldr] at h_holds ⊢
  norm_num at h_holds ⊢
  obtain ⟨c1, c2, c3, c4, c5, c6, c7, c8⟩ := h_holds
  rw [add_neg_eq_zero] at c1 c2 c3 c4 c5 c6 c7 c8
  have hx2 : env.get (i₀ + 1 + 1) = env.get i₀ ^ 2 := by rw [←c1, ←c2]; ring
  have hx3 : env.get (i₀ + 3 + 1 + 1) = env.get i₀ ^ 3 := by
    rw [←c3, c4, c5, hx2]; ring
  have hy2 : env.get (i₀ + 3 + 3 + 1 + 1) = env.get (i₀ + 3 + 3) ^ 2 := by
    rw [←c6, ←c7]; ring
  rw [hy2, hx3] at c8; exact c8.symm

theorem completeness (curveParams : Spec.CurveParams p) (idx : ℕ) : GeneralFormalCircuit.Completeness (F p) (elaborated curveParams idx) (Assumptions curveParams idx) := by
  circuit_proof_start
  simp only [List.sum, List.foldr] at *
  norm_num at *
  obtain ⟨he0, he1, he2⟩ := h_env
  have h0 := he0 (0 : Fin 3); have h1 := he0 (1 : Fin 3); have h2 := he0 (2 : Fin 3)
  have h3 := he1 (0 : Fin 3); have h4 := he1 (1 : Fin 3); have h5 := he1 (2 : Fin 3)
  have h6 := he2 (0 : Fin 3); have h7 := he2 (1 : Fin 3); have h8 := he2 (2 : Fin 3)
  simp only [toElements, circuit_norm, explicit_provable_type, Core.AllocMul.readRow, List.sum] at h0 h1 h2 h3 h4 h5 h6 h7 h8
  norm_num at h0 h1 h2 h3 h4 h5 h6 h7 h8
  try simp at h0 h1 h2 h3 h4 h5 h6 h7 h8
  rw [show i₀ + 1 + 1 = i₀ + 2 from by omega,
      show i₀ + 3 + 1 + 1 = i₀ + 3 + 2 from by omega,
      show i₀ + 3 + 3 + 1 + 1 = i₀ + 3 + 3 + 2 from by omega]
  rw [h0, h1, h2, h3, h4, h5, h6, h7, h8]
  simp only [Element.AllocSquare.Assumptions, Core.AllocMul.readRow] at h_assumptions
  obtain ⟨ha1, ⟨ha3, ha4⟩, ha6, ha8⟩ := h_assumptions
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
  · ring
  · rw [add_neg_eq_zero]; convert ha1 using 2 <;> try simp
  · ring
  · rw [add_neg_eq_zero]; convert ha3 using 2 <;> try simp
  · rw [add_neg_eq_zero]; convert ha4 using 2 <;> try simp
  · ring
  · rw [add_neg_eq_zero]; convert ha6 using 2 <;> try simp
  · rw [add_neg_eq_zero]; convert ha8 using 2 <;> try simp

def circuit (curveParams : Spec.CurveParams p) (idx : ℕ) : GeneralFormalCircuit (F p) unit Spec.Point :=
  {
    (elaborated curveParams idx) with
    Assumptions := Assumptions curveParams idx,
    Spec := (Spec curveParams),
    soundness := soundness curveParams idx,
    completeness := completeness curveParams idx
  }

end Ragu.Circuits.Point.Alloc
